// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuahhwkqatntfcoqypgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YWhod2txYXRudGZjb3F5cGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjMxMTcsImV4cCI6MjA3MjA5OTExN30.zTDkCjEFosFXpCtiSaDlhrVI8v6JZVTaWAqUb4ExZtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});